### ISSUE TITLE
jsarray bug

### ISSUE THREAD

**Issue by chacent** [samchon/tstl#8] opened 2017-11-17 09:24 UTC
let a = [3,4,6,2,1];
std.sort(std.begin(a),std.end(a))

end = first.source().size();
                                 ^

TypeError: first.source(...).size is not a function
    at Object.sort (D:\work\project3\type\node_modules\tstl\lib\tstl.js:528:34)
    at Object.<anonymous> (D:\work\project3\type\app.js:12:5)
    at Module._compile (module.js:566:14)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3

**Comment by chacent** [comment] 2017-11-17 09:44
function (std) {
    var JSArray;
    (function (JSArray) {
        var Iterator = (function () {
            function Iterator(source, index) {
                this.source_ = Object.create(source,{
                    size:{value:function(){
                        return this.length;
                    }},
                    at:{value:function(idx){
                        return this[idx];
                    }},
                    set:{value:function(idx,v){
                        this.__proto__[idx] = v;
                    }}
                });
                this.index_ = index;
            }

**Comment by samchon** [comment] 2017-11-22 01:33
`std.sort` is a modifier function and such modifier functions only accept STL containers' iterators.

Thus it's not a bug. `std.sort`, it only supports `std.vector` and `std.deque`

**Comment by chacent** [comment] 2017-11-22 02:11
i don't think so.
std.sort accept all iterators that support random accessed,for example c array.
so this is bug for JsArray adapter.
my second comment is one way to fix it. 
is it safe?

**Comment by samchon** [comment] 2017-11-22 06:04
I'm not familiar with pure JS code and I missed your nice idea. You made an adaptor for JS-Array. It seems very nice. I will adapt your idea at the next patch (v1.6.3). Taking advantage of full features of iterator pattern with JS-Array, it will be possible soon. Thanks very much.

**Comment by chacent** [comment] 2017-11-22 06:17
i see it. i thought that JsArray is implemented by you,isn't it? or it's implement by typescript?
i had not use typescript,but the build js file has JsArray class。

I had to thank you very much,your work is so great!
it's revolutionary for javascript! i had look for such a lib for lots of time!
though it's not very easy to use for jser,it's what js need and missed!
thank you very much!
you are the best of korea, and you are the best of asia! you are our pride！

**Comment by samchon** [comment] 2017-11-22 06:43
Your idea has implemented in the preview version. You can preview your idea with below command.

```bash
npm install --save tstl@next
```

The `v1.6.3` update will be released until this week. Thanks for your suggestion.

**Comment by chacent** [comment] 2017-11-22 06:45
thanks, i will try

**Comment by samchon** [comment] 2017-11-24 04:39
Your suggestion has implemented in the v1.6.3 update.

**Closed** 2017-11-24 04:39 UTC
Labels: enhancement
